### ISSUE TITLE
Erreur exception Messagerie directe

### ISSUE THREAD

**Issue by remikaze** [emeric254/Java-STRI-S4#49]
Quand émission d'un message vide et champ ip:port vide.
## `Messagerie directe

Entrez le port a utiliser :
14785

Entrez votre message ou <!q> pour quitter : 

Entrez ipv4:port : 

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
    at stri.java_connect.client.ClientMessagerieDirecte.emettreMsg(ClientMessagerieDirecte.java:78)
    at stri.java_connect.ihm.IHMConversation.messagerieDirecte(IHMConversation.java:64)
    at stri.java_connect.ihm.IHMConversation.<init>(IHMConversation.java:18)
    at stri.java_connect.ihm.IHM.afficherMenuMessagerie(IHM.java:229)
    at stri.java_connect.ihm.IHM.afficherMenuPrincipal(IHM.java:322)
    at stri.java_connect.ihm.IHM.afficherAccueil(IHM.java:80)
    at stri.java_connect.ihm.IHM.<init>(IHM.java:37)
    at stri.java_connect.AppClient.main(AppClient.java:22)`

**Comment by emeric254** [comment]
surement split() de la chaine saisie sans verification au prealable ...

**Comment by remikaze** [comment]
quand l'exception apparait, le code crash pas à 100% on peut troujours écrire mais rien ne se passe

**Comment by emeric254** [comment]
commit 810e2fa7569076c53b431ae2b04440bbefab594b
