### ISSUE TITLE
levée d'exception quand suppression profil

### ISSUE THREAD

**Issue by remikaze** [emeric254/Java-STRI-S4#52]
Quand on supprime un profil, le coté client se ferme normalement mais coté serveurAnnuaire, une échec apparait :

`SUPPRIMER /profils/thomas.maury@univ-tlse3.fr
java.lang.ArrayIndexOutOfBoundsException: 1
    at stri.java_connect.protocol.ProtocoleAnnuaire.validerRequeteLike(ProtocoleAnnuaire.java:223)
    at stri.java_connect.protocol.ControlleurProtocoleAnnuaire.traiterRequeteSuppression(ControlleurProtocoleAnnuaire.java:192)
    at stri.java_connect.protocol.ControlleurProtocole.traiterRequete(ControlleurProtocole.java:42)
    at stri.java_connect.server.ClientHandler.traitement(ClientHandler.java:86)
    at stri.java_connect.server.ClientHandler.communiquer(ClientHandler.java:62)
    at stri.java_connect.server.ClientHandler.run(ClientHandler.java:125)`

**Comment by emeric254** [comment]
commit 810e2fa7569076c53b431ae2b04440bbefab594b
